init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd
clone_depth: 1
os: Visual Studio 2015 CTP
test: off
deploy: off
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
